/*
	Below are the lists of allowed weapons for the weapon crates. Adjust them to your liking.
*/

//////////////////////////////////////////////////////////////////////////////////////////////
// Pistols
OKpistolList = ["Colt1911","glock17_EP1","M9","M9SD","Makarov","MakarovSD","revolver_EP1","UZI_EP1","UZI_SD_EP1"];

// Sniper Rifles
OKsniperList = ["SVD_Gh_DZ","DMR_DZ","M40A3_DZ","M107_DZ","M110_NVG_EP1","SCAR_H_LNG_Sniper","SCAR_H_LNG_Sniper_SD","BAF_LRR_scoped"];

// Light Machineguns
OKmgList = ["M240_DZ","M249_DZ","Mk48_DZ","Bizon_SD_DZ","MP5_SD_DZ","Pecheneg_DZ","PKM_DZ"];

// Primary Rifles
OKprimaryList = [
	"M16A4_ACOG_DZ",
	"M16A4_ACOG_DZ",
	"M16A4_ACOG_DZ",
	"M16A4_ACOG_DZ",
	"L85_Holo_DZ",
	"L85_Holo_DZ",
	"L85_Holo_DZ",
	"L85_Holo_DZ",
	"Bizon_SD_DZ",
	"Bizon_SD_DZ",
	"Bizon_SD_DZ",
	"Bizon_SD_DZ",
	"FN_FAL_ANPVS4_DZE",
	"FN_FAL_ANPVS4_DZE",
	"FNFAL_DZ",
	"FNFAL_DZ",
	"FNFAL_DZ",
	"FNFAL_DZ",
	"G36A_Camo_DZ",
	"G36A_Camo_DZ",
	"G36A_Camo_DZ",
	"G36K_Camo_DZ",
	"M16A2_GL_DZ",
	"M16A2_GL_DZ",
	"M16A2_GL_DZ",
	"M16A2_GL_DZ",
	"M4A1_AIM_SD_camo",
	"M4A1_AIM_SD_camo",
	"M4A1_AIM_SD_camo",
	"M4A1_AIM_SD_camo",
	"M14_DZ",
	"M14_DZ",
	"M14_DZ",
	"M4A1_HWS_GL_camo",
	"M4A1_HWS_GL_camo",
	"M4A1_HWS_GL_camo",
	"M4A1_HWS_GL_camo",
	"M4A3_CCO_EP1",
	"M4A3_CCO_EP1",
	"M4A3_CCO_EP1",
	"M4A3_CCO_EP1",
	"Sa58V_CCO_EP1",
	"Sa58V_CCO_EP1",
	"Sa58V_CCO_EP1",
	"Sa58V_RCO_EP1",
	"M79_EP1",
	"M32_EP1",
	"SCAR_H_CQC_CCO_SD",
	"SCAR_H_CQC_CCO_SD",
	"SCAR_H_CQC_CCO_SD",
	"SCAR_H_CQC_CCO_SD",
	"SCAR_H_STD_EGLM_Spect",
	"SCAR_H_STD_EGLM_Spect",
	"SCAR_H_STD_EGLM_Spect",
	"SCAR_H_STD_EGLM_Spect"
];

////////////////////////////////////////////////////////////////////////////////////////////////
// "supply" box
OKConTools = ["ItemToolbox","ItemCrowbar","ItemKnife","ItemEtool","ItemHatchet","ItemMatchbox","NVGoggles","ItemGPS","Binocular_Vector"];

OKConSupply = ["CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","MortarBucket","ItemTankTrap","ItemPole","PartGeneric","PartPlywoodPack","PartPlankPack","ItemSandbag","ItemWire","ItemJerrycan","PartEngine","PartFueltank","PartGlass","PartVRotor","PartWheel","ItemBriefcase100oz"];

////////////////////////////////////////////////////////////////////////////////////////////////
// "secret" box
OKSecret =
["ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemGoldBar",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemBriefcase10oz",
"ItemBriefcase20oz",
"ItemBriefcase30oz",
"ItemBriefcase40oz",
"ItemBriefcase50oz",
"ItemBriefcase60oz",
"ItemBriefcase70oz",
"ItemBriefcase80oz",
"ItemBriefcase90oz",
"ItemBriefcase100oz",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemDocument",
"ItemCitrine",
"ItemAmethyst",
"ItemObsidian"
];

// Only 1 from this list may enter in the "Secret" box. 
// The chance to get one item from this list is picking one item 
// from the set of the quantities per item summed together. See this example:
OKSecretRare = [
	["ItemDocument", 489],  // 97.8% chance to get a document. Equals 489/500 = 0.978
	["ItemTopaz", 10],	// 2% chance to get a Topaz. Equals 10/500 = 0.02
	["ItemSapphire",1]	// 0.2% chance to get a Sapphire. Equals 1/500 = 0.002
];

////////////////////////////////////////////////////////////////////////////////////////////////
// "cloth" box
OKCloth=[
"Skin_Bandit1_DZ",
"Skin_Bandit2_DZ",
"Skin_BanditW1_DZ",
"Skin_BanditW2_DZ",
"Skin_Camo1_DZ",
"Skin_CZ_Soldier_Sniper_EP1_DZ",
"Skin_CZ_Special_Forces_GL_DES_EP1_DZ",
"Skin_Drake_Light_DZ",
"Skin_FR_OHara_DZ",
"Skin_FR_Rodriguez_DZ",
"Skin_Functionary1_EP1_DZ",
"Skin_Graves_Light_DZ",
"Skin_GUE_Commander_DZ",
"Skin_GUE_Soldier_2_DZ",
"Skin_GUE_Soldier_CO_DZ",
"Skin_GUE_Soldier_Crew_DZ",
"Skin_GUE_Soldier_MG_DZ",
"Skin_GUE_Soldier_Sniper_DZ",
"Skin_Ins_Soldier_GL_DZ",
"Skin_Pilot_EP1_DZ",
"Skin_Priest_DZ",
"Skin_Rocker1_DZ",
"Skin_Rocker2_DZ",
"Skin_Rocker3_DZ",
"Skin_Rocker4_DZ",
"Skin_Rocket_DZ",
"Skin_RU_Policeman_DZ",
"Skin_Sniper1_DZ",
"Skin_Soldier1_DZ",
"Skin_Soldier_Bodyguard_AA12_PMC_DZ",
"Skin_Soldier_Sniper_PMC_DZ",
"Skin_Soldier_TL_PMC_DZ",
"Skin_SurvivorW3_DZ",
"Skin_SurvivorWcombat_DZ",
"Skin_SurvivorWdesert_DZ",
"Skin_SurvivorWpink_DZ",
"Skin_SurvivorWurban_DZ",
"Skin_TK_INS_Soldier_EP1_DZ",
"Skin_TK_INS_Warlord_EP1_DZ"
];

////////////////////////////////////////////////////////////////////////////////////////////////
// EMS Stuff
OKEMSToolsCon = ["ItemToolbox","ItemCrowbar","ItemKnife","ItemEtool","ItemHatchet","ItemMatchbox","NVGoggles","ItemGPS","Binocular_Vector"];

OKEMSSupplyCon = ["CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","CinderBlocks","MortarBucket","ItemTankTrap","ItemPole","PartGeneric","PartPlywoodPack","PartPlankPack","ItemSandbag","ItemWire","ItemJerrycan","PartEngine","PartFueltank","PartGlass","PartVRotor","PartWheel","ItemBriefcase100oz"];

OKEMSWeaponry = ["M107_DZ","M110_NVG_EP1","M4A3_RCO_GL_EP1","SCAR_H_LNG_Sniper","M16A4_ACG_GL","SCAR_H_LNG_Sniper_SD","M79_EP1","SCAR_H_STD_EGLM_Spect","M32_EP1","SCAR_H_CQC_CCO_SD"];

OKEMSMedicals = ["ItemBandage","ItemMorphine","ItemEpinephrine","ItemPainkiller","FoodMRE","ItemSodaCoke","ItemAntibiotic","ItemBloodbag","ItemBriefcase100oz"]

