class CfgTraderCategory {
	#include "Category\Hero.hpp"
	#include "Category\Bandit.hpp"
	#include "Category\BlackMarket.hpp"
	#include "Category\Weapons.hpp"
	#include "Category\Ammunition.hpp"
	#include "Category\GeneralStore.hpp"
	#include "Category\MedicalSupplies.hpp"
	#include "Category\Parts.hpp"
	#include "Category\Vehicles.hpp"
	#include "Category\AirVehicles.hpp"
	#include "Category\Boats.hpp"
	#include "Category\Wholesale.hpp"
	#include "Category\SuperBanditAmmo.hpp"
	#include "Category\SuperBanditAntiAirAmmo.hpp"
	#include "Category\SuperBanditAntiAirWeapons.hpp"
	#include "Category\SuperBanditAntiTankAmmo.hpp"
	#include "Category\SuperBanditAntiTankWeapons.hpp"
	#include "Category\SuperBanditArmored.hpp"
	#include "Category\SuperBanditHelicopters.hpp"
	#include "Category\SuperHeroAmmo.hpp"
	#include "Category\SuperHeroAntiAirAmmo.hpp"
	#include "Category\SuperHeroAntiAirWeapons.hpp"
	#include "Category\SuperHeroAntiTankAmmo.hpp"
	#include "Category\SuperHeroAntiTankWeapons.hpp"
	#include "Category\SuperHeroArmored.hpp"
	#include "Category\SuperHeroHelicopters.hpp"
};
